# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  elixir:
    docker:
      - image: circleci/elixir:1.6
      - image: circleci/postgres:10.3

    working_directory: ~/repo
    steps:
      - checkout

        # specify any bash command here prefixed with `run: `
      - run: mix deps.get
      - run: mix ecto.create
      - run: mix test
