# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.6-node-browsers
      - image: circleci/postgres:10.3

    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - elixir-build-v3-{{ checksum "mix.lock" }}


      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix ecto.create

      - run: cd assets && yarn

      - run: mix verify

      - save_cache:
          key: elixir-build-v3-{{ checksum "mix.lock" }}
          paths:
            - '_build'
            - 'deps'
            - '~/.mix'
